### ISSUE TITLE
Search Functionality

### ISSUE THREAD

**Issue by jeetdholakia** [KeenenCharles/AndroidUnplash#1]
Hi,

First of all, thanks for the library, I've been looking for a painless way to integrate unsplash in my apps, I cannot see the search feature though? Do you have it in the library?

**Comment by KeenenCharles** [comment]
Hey, glad you find it useful and yes you can search using the searchPhotos() function. 
Example:

```
unsplash.searchPhotos("ocean", 1 /*page number*/, 10 /*per page*/, new Unsplash.OnPhotosLoadedListener() {
            @Override
            public void onComplete(List<Photo> photos) {
                
            }

            @Override
            public void onError(String error) {

            }
        });
```

I'll add some more examples to the readme.

**Comment by KeenenCharles** [comment]
Hey, there was a bug in the search functionality that I just fixed and uploaded a new version of the library. Just update your version to 0.1.1 and take a look at the example for searching in the readme.
