### ISSUE TITLE
Get next page using searchPhotos

### ISSUE THREAD

**Issue by midds109** [KeenenCharles/AndroidUnplash#10]
Thanks KeenenCharles for the wonderful library. I am using the **searchPhotos** for retrieving images. Could you please let me know how to get the next page of images as I am always getting the first page. In unsplash API there is an option to get specific pages with optional parameter **page**. So I tied adding the query for search images as **travel&page=2** but then it's not retrieving the photos specific to the search keyword but I am getting pages.

**Comment by KeenenCharles** [comment]
Were you able to figure this out? Just noticed the issue.
