### ISSUE TITLE
Get random photo id from search

### ISSUE THREAD

**Issue by sicksand** [KeenenCharles/AndroidUnplash#11]
Hi,
How do I get a random photo id from a search query without I have to iterate the json and put it into the array and get the id.

Thanks

**Comment by KeenenCharles** [comment]
I don't think there's any way to do this with the search API. You can use getRandomPhoto but that might not suit your needs.

**Comment by sicksand** [comment]
Hi Keenen

Here is what I do

```String[] query = {"android wallpaper", "iphone wallpaper", "phone wallpaper"};
        String randQuery = query[(int)(Math.random() * query.length)];
        Log.d(TAG,"Querying.... " + randQuery);
        Random rand = new Random();
        idx = rand.nextInt(Integer.valueOf(20));

        unsplash.searchPhotos(randQuery, idx, 20, Unsplash.ORIENTATION_PORTRAIT, new Unsplash.OnSearchCompleteListener() {
            @Override
            public void onComplete(SearchResults results) {
                //
                Log.d(TAG, "Total Results Found " + results.getTotal());


                List<Photo> photos = results.getResults();
                //photos.get().
                Log.d(TAG, "Photo random id " +  idx);
                randPhotoId = photos.get(idx).getId();```

**Comment by KeenenCharles** [comment]
Ah yeah I think getRandomPhoto will do what you need. 
Try
unsplash.getRandomPhoto(null, null, null, null, null, null, Unsplash.ORIENTATION_PORTRAIT, new Unsplash.OnPhotoLoadedListener() {
@Override
public void onComplete(Photo photo) {

}
});

**Comment by KeenenCharles** [comment]
Awesome! I'll add a link to it to the Readme as an app built with this library
