### ISSUE TITLE
Callback for 404 error code

### ISSUE THREAD

**Issue by disparate** [KeenenCharles/AndroidUnplash#12]
Currently there is no option to get a callback for 404 error.
```
@Override
public void onResponse(Call<SearchResults> call, Response<SearchResults> response) {
   int statusCode = response.code();
   Log.d(TAG, "Status Code = " + statusCode);
   if(statusCode == 200) {
      SearchResults results = response.body();
      listener.onComplete(results);
   }
   else if(statusCode == 401) {
      Log.d(TAG, "Unauthorized, Check your client Id");
   }
}
```
Maybe we should invoke listener.onError(statusCode) if it's not 200?

**Comment by KeenenCharles** [comment]
Yeah, definitely it should do that. 
I'll see if I can get some time to add this but you're free to submit a PR if you can.

**Comment by disparate** [comment]
Have a look pls.
https://github.com/KeenenCharles/AndroidUnplash/pull/13

**Comment by KeenenCharles** [comment]
Version 1.0.4 is up now with your changes
