### ISSUE TITLE
Parser

### ISSUE THREAD

**Issue by ArensDemaliaj** [KeenenCharles/AndroidUnplash#18]
I am kinda new to this API. I just tested the following code and it seems to work. I just dont know how to use the List<Photo> photos. Do i need a parser? How can i display them in a list? I need some kinda help with that. @KeenenCharles 

```
 unsplash.getPhotos(1, 10, Order.LATEST, new Unsplash.OnPhotosLoadedListener() {
            @Override
            public void onComplete(List<Photo> photos) {
                int photoCount = photos.size();
            }

            @Override
            public void onError(String error) {
                Log.v("Error", error);
            }
        });
```

**Comment by KeenenCharles** [comment]
Once you get the list of photos you can display it however you like. If you want to display it in a list look into creating a RecyclerView for it. You can see an example of it in the sample project here https://github.com/KeenenCharles/AndroidUnplash/tree/master/app/src/main/java/com/kc/unsplashdemo

**Comment by ArensDemaliaj** [comment]
👌
