### ISSUE TITLE
Pages

### ISSUE THREAD

**Issue by SajjadMohammed** [KeenenCharles/AndroidUnplash#19]
Hi, how can I get the next page of specific collection?

**Comment by KeenenCharles** [comment]
You'll need to call `getCollectionPhotos` and specify the page number

**Comment by SajjadMohammed** [comment]
Ok, but what of meaning 403 when I getting photos first time?

**Comment by KeenenCharles** [comment]
Can you share the code you're using?

**Comment by SajjadMohammed** [comment]
`private void loadImages(int page) {
        UnSplashModel.unsplash
                .getCollectionPhotos(getCollectionId(), page, 10, new Unsplash.OnPhotosLoadedListener() {
                    @Override
                    public void onComplete(final List<Photo> photos) {
                        photoList = new ArrayList<>();
                        for (Photo photo : photos) {
                            photoList.add(
                                    new PhotoItemModel(photo.getLikes()
                                            , photo.getUrls().getThumb()
                                            , photo.getUrls().getSmall()
                                            , photo.getUrls().getRegular()));
                        }
                        collectionsRecyclerAdapter = new CollectionsRecyclerAdapter(getActivity(), photoList);
                        collectionsRecycler.setAdapter(collectionsRecyclerAdapter);
                        collectionProgressBar.setVisibility(View.GONE);
                        shouldLoadMore = true;
                    }

                    @Override
                    public void onError(String error) {
                        shouldLoadMore = false;
                        Toast.makeText(getActivity(), error, Toast.LENGTH_LONG).show();
                    }
                });
    }`

**Comment by KeenenCharles** [comment]
Are you trying to access a private collection?

That code works for me with a public collection ID.
