### ISSUE TITLE
Gson Crash

### ISSUE THREAD

**Issue by jeetdholakia** [KeenenCharles/AndroidUnplash#2]
Hi,
 
Version 0.1.1 was running fine for a certain number of times but now I'm getting this error
`No virtual method newJsonReader(Ljava/io/Reader;)Lcom/google/gson/stream/JsonReader; in class Lcom/google/gson/Gson; or its super classes`

I'm assuming you have a gradle dependency of gson version (2.8) which is not supported? The latest it shows on maven central is 2.7

**Comment by KeenenCharles** [comment]
I removed the gson dependency since it wasn't needed anymore. You can upgrade to version 0.1.2 and let me know if that solves the issue.

**Comment by jeetdholakia** [comment]
Same issue...

**Comment by KeenenCharles** [comment]
Have you tried cleaning and rebuilding your project?
