### ISSUE TITLE
Crash with NullPointerException

### ISSUE THREAD

**Issue by mhdhejazi** [KeenenCharles/AndroidUnplash#26]
When the response has an error, the client crashes with a NPE:

> java.lang.NullPointerException: null cannot be cast to non-null type com.google.gson.JsonElement
        at com.kc.unsplash.api.UnsplashCallback.onResponse(UnsplashCallback.kt:22)

When I debugged the issue, I found that `response.body()` is indeed `null` here:
https://github.com/KeenenCharles/AndroidUnplash/blob/53c018c363573a296e3b82e27084265ece0cc206/androidunsplash/src/main/java/com/kc/unsplash/api/UnsplashCallback.kt#L21-L24

After taking a look at other methods, I guess `response.errorBody()` should be used here instead as we're dealing with an "unsuccessful response":

![image](https://user-images.githubusercontent.com/121827/107788972-10bd5c00-6d62-11eb-98ad-a0599e4c6b6f.png)

**Comment by mhdhejazi** [comment]
Also, is it intended to only log the error without calling `onError` or `onComplete`? How would the caller know about the issue?

**Comment by KeenenCharles** [comment]
Thanks for sharing. This should be fixed in version 2.0.4
