### ISSUE TITLE
Unsplash.collections.get API Call Failure

### ISSUE THREAD

**Issue by mmobin789** [KeenenCharles/AndroidUnplash#28]
Hi,

This API call suddenly stopped working without any reason using Unsplash.photos.get now.

Also was using an older version of your lib updated to latest 3.0.0 but issue exists in both.

Error is a number format exception with some string.

This is not urgent for me but this is more of a FYI because I am using images for testing only so they are irrelevant.

Thanks.

**Comment by KeenenCharles** [comment]
Thanks for letting me know. Unsplash changed the collection ID to a string format and that caused an issue. It should be fixed in version 3.0.1
