### ISSUE TITLE
Not An Issue! But Want to Download Images

### ISSUE THREAD

**Issue by PratikSymz** [KeenenCharles/AndroidUnplash#3]
I took help of your API Model to make my wallpaper app but now I want to download and save the photos using the the link I received from getPhotoDownloadLink() and I'm really confused. So, could you kindly help me with this. Thank You.

**Comment by KeenenCharles** [comment]
Take a look at the Android Download Manager. It lets you download files from a URL like the one you get from getPhotoDownloadLink() and save it on the device.

**Comment by PratikSymz** [comment]
Thanks a lot I used your advice and applied the feature, but I'm getting an error hope you can help me with that.

CODE PIECE:-
holder.photoDownloadButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                unsplashService.getPhotoDownloadLink(photo.getId(), new Unsplash.OnLinkLoadedListener() {
                    @Override
                    public void onComplete(String downloadLink) {
                        DownloadManager.Request downloadImageRequest = new DownloadManager.Request(
                                Uri.parse(downloadLink)
                        );

                        downloadImageRequest.setTitle("Image Downloaded!");
                        downloadImageRequest.setDescription("Image is being downloaded!");

                        downloadImageRequest.allowScanningByMediaScanner();
                        downloadImageRequest.setNotificationVisibility(
                                DownloadManager.Request.VISIBILITY_VISIBLE_NOTIFY_COMPLETED
                        );
                        downloadImageRequest.setDestinationInExternalPublicDir(
                                Environment.DIRECTORY_DOWNLOADS,
                                DIRECTORY_NAME
                        );

                        DownloadManager downloadManager = (DownloadManager)
                                mContext.getSystemService(Context.DOWNLOAD_SERVICE);
                        if (downloadManager != null) {
                            downloadManager.enqueue(downloadImageRequest);
                        }
                        Log.d("Download: ", "Image Downloaded & Saved");
                    }

                    @Override
                    public void onError(String error) {
                        Log.d(TAG, " Unable To Download Image: " + error);
                    }
                });
            }
        });

ERROR:-
"Expected a string but was BEGIN_OBJECT at line 1 column 2 path $"

**Comment by KeenenCharles** [comment]
Sounds like a decoding error somewhere. Maybe while downloading the image I can't say for sure. I'd look at the download link you get and make sure it works.

**Comment by ChrisClarke9000** [comment]
Hi,

I'm trying to do something very similar but get the same error message - "Expected a string but was BEGIN_OBJECT at line 1 column 2 path $"

I must point out that I don't actually get a link with getPhotoDownloadLink() - it never onComplete()'s and just onError()'s (confirmed with Log.d()'s).

The id i'm feeding getPhotoDownloadLink() comes from photos.get(position).getId() and looks something like "l1Ld1Olb42I".

I'm at a loss as to how to proceed. :/

Thanks

**Comment by PratikSymz** [comment]
I know @ChrisClarke9000 it happened with me too. The reason is that it's returning an object instead of a string for the download link which means we have to create an object model for the download link which should've been done in the first place but it's okay because he provided all of the data models except one which can be done by us because of the existing one's. So here is the data model I made according to the one's made by @KeenenCharles using Parcelables ->

**DownloadUrls.java -->**
import android.os.Parcel;
import android.os.Parcelable;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

public class DownloadUrl implements Parcelable {

    @SerializedName("url")
    @Expose
    private String url;

    public final static Creator<DownloadUrl> CREATOR = new Creator<DownloadUrl>() {
        @SuppressWarnings({
                "unchecked"
        })
        public DownloadUrl createFromParcel(Parcel in) {
            DownloadUrl instance = new DownloadUrl();
            instance.url = ((String) in.readValue((String.class.getClassLoader())));
            return instance;
        }

        @Override
        public DownloadUrl[] newArray(int size) {
            return (new DownloadUrl[size]);
        }
    };

    /**
     * No args constructor for use in serialization
     */
    public DownloadUrl() {
    }

    /**
     * @param url
     */
    public DownloadUrl(String url) {
        super();
        this.url = url;
    }

    public String getDownloadUrl() {
        return url;
    }

    public void setDownloadUrl(String url) {
        this.url = url;
    }

    public DownloadUrl withDownloadUrl(String url) {
        this.url = url;
        return this;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(url);
    }
}


**Unsplash.java -->**

1. Callback -->
private Callback<DownloadUrl> getPhotoDownloadLinkCallback(final OnLinkLoadedListener listener){
        return new Callback<DownloadUrl>() {
            @Override
            public void onResponse(Call<DownloadUrl> call, Response<DownloadUrl> response) {
                int statusCode = response.code();
                Log.d(TAG, "Status Code = " + statusCode);
                if(statusCode == 200) {
                    DownloadUrl downloadUrl = response.body();
                    listener.onComplete(downloadUrl);
                }
                else if(statusCode == 401) {
                    Log.d(TAG, "Unauthorized, Check your client Id");
                }
            }

            @Override
            public void onFailure(Call<DownloadUrl> call, Throwable t) {
                listener.onError(t.getMessage());
            }
        };
    }

2. Use -->
public void getPhotoDownloadLink(@NonNull String id, final OnLinkLoadedListener listener){
        Call<DownloadUrl> call = photosApiService.getPhotoDownloadLink(id);
        call.enqueue(getPhotoDownloadLinkCallback(listener));
    }

I know the code might be mediocre and a bit confusing because I had no idea about what I was doing.
Hopefully you can understand it and help me improve this code.
