### ISSUE TITLE
Question about tracking downloads

### ISSUE THREAD

**Issue by SeanBlahovici** [KeenenCharles/AndroidUnplash#30]
Hey there, great library!

From the Unsplash guidelines, I see we must trigger a "trackDownload" call when one of our users selects/uses a specific photo. At first glance, I have not found a way to do this through this library. Is it included somewhere? Thanks!

Edit: Is it possible that the Unsplash.photos.search with query, which returns a payload with download links, does this automatically track downloads?

**Comment by KeenenCharles** [comment]
Hey Sean you can track downloads by calling the getDownloadLink() function with the id of the photo
