### ISSUE TITLE
SSL Handshake Error on API < 21

### ISSUE THREAD

**Issue by DrAxeY** [KeenenCharles/AndroidUnplash#5]
I get the following error on devices with API < 21. Any suggestion on how to fix it?

```
avax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb85abd70: Failure in SSL library, usually a protocol error
error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version (external/openssl/ssl/s23_clnt.c:741 0x8c7ae990:0x00000000)
```

**Comment by KeenenCharles** [comment]
Hey sorry for the late response. Unsplash API must not support TLS 1.1. You'd have to manually enable TLS 1.2 support for devices with API < 21. It'd have to be done in the library itself so feel free to fork and add it if you can. I'll take a look at it when I get some time.
