### ISSUE TITLE
Page number limited to 1

### ISSUE THREAD

**Issue by friskycoder** [KeenenCharles/AndroidUnplash#7]
The number of photos that the method  getPhotos() and other methods load are limited to page 1 and only load fiew photos ...is there any way to increase the number of photos

**Comment by KeenenCharles** [comment]
When calling getPhotos the first parameter is the page and the 2nd is the number per page. Try the following code

unsplash.getPhotos(2, 20, Order.POPULAR, new Unsplash.OnPhotosLoadedListener() {
            @Override
            public void onComplete(List<Photo> photos) {
            }

            @Override
            public void onError(String error) {

            }
        });

**Comment by friskycoder** [comment]
Thank you for the reply

Yeh am using it that way the page changes but the number of photos per page
is limited to 20 even if per page 100 is given.I need photos to generate
continuosly.

**Comment by KeenenCharles** [comment]
It looks like Unsplash has a limit of how much you can request per page. 30 worked for me but I can't get any more than that

**Comment by velocity24** [comment]
Yeh max 30 for me too...is there any way i can get photos continuosly.Like is there any options to get photos randomly or so that are not limited to a single page so that the number of photos can go on.It would be really helpful.

**Comment by friskycoder** [comment]
Yeh max 30 for me too...is there any way i can get photos continuosly.Like is there any options to get photos randomly or so that are not limited to a single page so that the number of photos can go on.It would be really helpful.

**Comment by KeenenCharles** [comment]
You need to implement pagination in your app. After you get the first page of 30 photos, make a request for page 2 with 30 more photos and add it to the list of photos.

**Comment by friskycoder** [comment]
Sorry for asking, but I have no idea how it's done, kinda new to this.Could
you please show me an example.

**Comment by KeenenCharles** [comment]
This article explains it pretty well. You'd just need to replace the API calls in the article with calls to the Unsplash library like above
https://medium.com/@etiennelawlor/pagination-with-recyclerview-1cb7e66a502b

**Comment by KeenenCharles** [comment]
Yeah that's it but a couple things you should look at
1. You don't want to hardcode the page number as 2 because then it will only fetch the same images. You should have a variable that stores the page number and is incremented by 1 each time getPhotos is called

2. You shouldn't create and set a new adapter each time as it will only show the new images loaded. The adapter should be global and you should set the adapter to the recyclerview once outside of this function. You should look into how to add new items to an adapter and in the OnComplete where you currently create a new adapter you should just add the new items to the global adapter.

**Comment by friskycoder** [comment]
The pages are now loading but replace the previous loaded ones

**Comment by KeenenCharles** [comment]
Nice!

**Comment by charmas3r** [comment]
> Ah finally got it working, Thankyou Keenen for the help.

Can you include your final method which got this working? Looking to implement something simillar but have never worked with pagination.

**Comment by ArensDemaliaj** [comment]
> Ah finally got it working, Thankyou Keenen for the help.
Can you include your final method which got this working?
