### ISSUE TITLE
getting user profile pic

### ISSUE THREAD

**Issue by velocity24** [KeenenCharles/AndroidUnplash#8]
how can i get the user profile pic and display it on imageview
tried   final ProfileImage proImage =photo.getUser().getProfileImage();

**Comment by KeenenCharles** [comment]
After you get the profile image you can use .getLarge(), getMedium() or .getSmall() to get the url to the profile photo then you can display it on the imageview.

**Comment by KeenenCharles** [comment]
You need to call getCollectionPhotos with the collection id

**Comment by velocity24** [comment]
Nice!!.Could you please give an exaple for getting date and location

**Comment by KeenenCharles** [comment]
For a photo try getCreatedDate() & getLocation()
